# Welcome to Jekyll!
#

# Site settings
title: dokupe
description: 스스로 구축하는 모바일 네트워크 프로젝트.
owner: Yechan Kim (kycfeel) # or company name
first_published: 2017 # if migrating another site, the year of your first publish
email: kycfeel@gmail.com
baseurl: "/dokupe" # the subpath of your site, e.g. /blog
url: "https://kycfeel.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/dokupe
  github: https://github.com/kycfeel
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
